import java.awt.Color;
/**
 * Program to create a Body Mass Index Calculator
 * Author: Jermaine Grant
 */
public class BMI_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form BMI_Calculator
     */
    public BMI_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextHeight = new javax.swing.JTextField();
        jTextWeight = new javax.swing.JTextField();
        jTextBMI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        jLabel2.setText("Body Mass Index Calculator");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 54, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 120));

        jButton1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jButton1.setText("Calculate BMI");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 519, 240, 80));

        jButton2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 230, 80));

        jButton3.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jButton3.setText("ESC");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 230, 80));

        jTextHeight.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jTextHeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHeightActionPerformed(evt);
            }
        });
        getContentPane().add(jTextHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 180, 70));

        jTextWeight.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jTextWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 180, 70));

        jTextBMI.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jTextBMI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBMIActionPerformed(evt);
            }
        });
        getContentPane().add(jTextBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 180, 70));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel1.setText("Enter Height in Metres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel3.setText("Enter Weight in Kg");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setText("Your BMI Result:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 210, 40));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jToolBar1.setRollover(true);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTable1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Underweight", "15 - 18.9"},
                {"Average", "19 - 24.9"},
                {"Overweight", "25 - 29.9"},
                {"Obese", "30 - 39.9"},
                {"Morbidly obese", ">=40"}
            },
            new String [] {
                "Body Type", "BMI Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jToolBar1.add(jScrollPane1);

        jTabbedPane1.addTab("BMI Table", jToolBar1);

        jToolBar2.setRollover(true);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTable2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"19 - 24", "19 - 24"},
                {"25 - 34", "20 - 25"},
                {"35 - 44", "21 - 26"},
                {"45 - 54", "22 - 27"},
                {"55 - 60 ", "23 - 28"}
            },
            new String [] {
                "Age Range", "BMI Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jToolBar2.add(jScrollPane2);

        jTabbedPane1.addTab("BMI Table NCI", jToolBar2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 383, 180));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        double myHeight = Double.parseDouble(jTextHeight.getText());
        double myWeight = Double.parseDouble(jTextWeight.getText());
        double myBMI = myWeight / (myHeight * myHeight);

        String calculate_BMI = String.format("%.2f", myBMI);
        jTextBMI.setText(calculate_BMI);
        
        if (myBMI <= 18.9)
        {
            jTextBMI.setOpaque(true);
            jTextBMI.setBackground(Color.pink);
        }
        

        else if (myBMI <= 24.9)
        {
            jTextBMI.setOpaque(true);
            jTextBMI.setBackground(Color.green);
        }

        else if (myBMI <= 29.9)
        {
            jTextBMI.setOpaque(true);
            jTextBMI.setBackground(Color.orange);
        }

        else if (myBMI <= 39.9)
        {
            jTextBMI.setOpaque(true);
            jTextBMI.setBackground(Color.yellow);

        }

        else if (myBMI >= 40)
        {
            jTextBMI.setOpaque(true);
            jTextBMI.setBackground(Color.red);
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextHeight.setText(null);
        jTextWeight.setText(null);
        jTextBMI.setText(null);
        jTextBMI.setOpaque(true);
        jTextBMI.setBackground(null);
    }                                        
// Code for the escape button to terminate calculator
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);        
    }                                        

    private void jTextHeightActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextBMIActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextBMI;
    private javax.swing.JTextField jTextHeight;
    private javax.swing.JTextField jTextWeight;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration                   
}
